/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import modelo.Conexion;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;

public class MenuPpal extends javax.swing.JFrame {
/*  */
   
    public MenuPpal() {
        initComponents();
        MostrarComuna();
        txtIdComunas.setVisible(false);
                
        //Tabla de categoria Articulos
        try{    
            DefaultTableModel modelo1 = new DefaultTableModel();
            
            TableCategoriaArt.setModel(modelo1);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            String sql = "SELECT * FROM categoria_articulo";
            
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int CantidadColumnas = rsMd.getColumnCount();
            
            modelo1.addColumn("Id");
            modelo1.addColumn("Categoria");
            
            while(rs.next()){
                
                Object[] filas = new Object[CantidadColumnas];
                
                for(int i=0; i < CantidadColumnas; i++){
                    filas[i] = rs.getObject(i + 1);
                }
                modelo1.addRow(filas); 
            }
        
        
        }catch(SQLException ex){
            System.err.println(ex.toString());
        }
        
        
        //Tabla de Articulos
        try{    
            DefaultTableModel modelo2 = new DefaultTableModel();
            
            TableArticulo.setModel(modelo2);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            String sql = "SELECT * FROM articulo";
            
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int CantidadColumnas = rsMd.getColumnCount();
            
            modelo2.addColumn("Codigo");
            modelo2.addColumn("Nombre");
            modelo2.addColumn("Categoria");
            modelo2.addColumn("Stock");
            modelo2.addColumn("Fecha Vencimiento");
            
            while(rs.next()){
                
                Object[] filas = new Object[CantidadColumnas];
                
                for(int i=0; i < CantidadColumnas; i++){
                    filas[i] = rs.getObject(i + 1);
                }
                modelo2.addRow(filas); 
            }
        
        
        }catch(SQLException ex){
            System.err.println(ex.toString());
        }
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void MostrarComuna(){
    
     //Tabla de Comunas
        try{    
            DefaultTableModel modelo6 = new DefaultTableModel();
            
            TablaComuna.setModel(modelo6);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            String sql = "SELECT * FROM comunas";
            
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int CantidadColumnas = rsMd.getColumnCount();
            
            modelo6.addColumn("Codigo");
            modelo6.addColumn("Cod_Comunas");
            modelo6.addColumn("Nombre");
            modelo6.addColumn("Estado");
                        
            while(rs.next()){
                
                Object[] filas = new Object[CantidadColumnas];
                
                for(int i=0; i < CantidadColumnas; i++){
                    filas[i] = rs.getObject(i + 1);
                }
                modelo6.addRow(filas); 
            }
        
        
        }catch(SQLException ex){
            System.err.println(ex.toString());
        }
        
    
    
    }
    
    // * Radio Button Comunas ***
    public String guardarRadioBotonComunas(){
 
        String valor="1";
        if(rbtnActivoComuna.isSelected()==true){
           valor= "1";
           
        }else if (rbtnInactivoComuna.isSelected()==true){
            valor = "0";
        }
       
        return valor;
    }
    
    
    //**** Llamar Datos Comunas ********
    public void llamarDatosComunas(){
        try{
            int fila = TablaComuna.getSelectedRow();
            int ID = (int) TablaComuna.getValueAt(fila, 0);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            String sql = "SELECT * FROM comunas WHERE (idcomunas = ?)";
            
            ps = con.prepareStatement(sql);
            ps.setInt(1, ID);
            rs = ps.executeQuery();
            
            while(rs.next()){
                
                txtIdComunas.setText(String.valueOf(rs.getString("idcomunas")));
                txtNombreComuna.setText(rs.getString("nombre_comunas"));
                txtCodigoComuna.setText(rs.getString("codigo_comunas"));
                if(rs.getString("com_estado").equals("1")){
                    rbtnActivoComuna.setSelected(true);
                }else if(rs.getString("com_estado").equals("0")){
                    rbtnInactivoComuna.setSelected(true);
                }
            }
            
        }catch(SQLException ex){
            System.err.println(ex.toString());
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btnGroupComunas = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelClientes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nombre = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombresClientes = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txtApellidosClientes = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtFechaNacimento = new javax.swing.JTextField();
        rActivo = new javax.swing.JRadioButton();
        rInactivo = new javax.swing.JRadioButton();
        jPanelProveedores = new javax.swing.JPanel();
        jPanelCategoriaArticulos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreCategoriaArt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableCategoriaArt = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jPanelPacks = new javax.swing.JPanel();
        jPanelCategoriaPacks = new javax.swing.JPanel();
        jPanelRRSS = new javax.swing.JPanel();
        txtRRSS = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        cbxRRSS = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();
        txtBusqudaRS = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        ScrollTblRsResultado = new javax.swing.JScrollPane();
        TblRsResultado = new javax.swing.JTable();
        ChkInactivo = new javax.swing.JCheckBox();
        jPanelBancos = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEntidadBancaria = new javax.swing.JTextField();
        jCBoxEstado = new javax.swing.JComboBox<>();
        btnIngresar1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDatosBnc = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnMenuInicio = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jPanelEstados_Ventas = new javax.swing.JPanel();
        jPanelUsuario = new javax.swing.JPanel();
        jPanelArticulos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreArticulo = new javax.swing.JTextField();
        txtStockArticulo = new javax.swing.JTextField();
        ComboBoxArticulo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFechaArticulo = new javax.swing.JTextField();
        CheckBoxVencimientoArticulo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableArticulo = new javax.swing.JTable();
        btnIngregarArticulo = new javax.swing.JButton();
        txtCategoriaArt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanelComunas = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        btnIngresarComuna = new javax.swing.JButton();
        txtCodigoComuna = new javax.swing.JTextField();
        txtNombreComuna = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonMenuInicio = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarComunas = new javax.swing.JTextField();
        btnBuscarComuna = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaComuna = new javax.swing.JTable();
        btnModComuna = new javax.swing.JButton();
        btnLimpiarComuna = new javax.swing.JButton();
        rbtnActivoComuna = new javax.swing.JRadioButton();
        rbtnInactivoComuna = new javax.swing.JRadioButton();
        txtIdComunas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(203, 204, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Registro de clientes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        nombre.setText("Nombre");

        jLabel13.setText("Apellido");

        jLabel14.setText("Rut");

        jLabel15.setText("Mail");

        txtNombresClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresClientesActionPerformed(evt);
            }
        });

        txtApellidosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosClientesActionPerformed(evt);
            }
        });

        jLabel16.setText("Direccion");

        jLabel17.setText("Telefono");

        jLabel18.setText("Fecha de nac");

        jLabel19.setText("Estado");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton3.setText("jButton2");

        jButton4.setText("jButton2");

        jLabel20.setText("Buscar Rut");

        rActivo.setText("Activo");

        rInactivo.setText("Inactivo");

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(196, 196, 196))
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtNombresClientes)
                            .addComponent(txtMail)
                            .addComponent(txtDireccion)
                            .addComponent(txtRut))
                        .addGap(50, 50, 50)
                        .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelClientesLayout.createSequentialGroup()
                                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtFechaNacimento)
                                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                                        .addComponent(rActivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rInactivo))))
                            .addComponent(btnGuardar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 293, Short.MAX_VALUE))))
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(txtNombresClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtApellidosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtFechaNacimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rActivo)
                            .addComponent(rInactivo)))
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addGap(2, 2, 2)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)))
        );

        jTabbedPane1.addTab("Clientes", jPanelClientes);

        javax.swing.GroupLayout jPanelProveedoresLayout = new javax.swing.GroupLayout(jPanelProveedores);
        jPanelProveedores.setLayout(jPanelProveedoresLayout);
        jPanelProveedoresLayout.setHorizontalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanelProveedoresLayout.setVerticalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Proveedores", jPanelProveedores);

        jPanelCategoriaArticulos.setBackground(new java.awt.Color(153, 204, 255));

        jLabel10.setText("Nombre de la categoria");

        TableCategoriaArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableCategoriaArt);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Insertar");

        javax.swing.GroupLayout jPanelCategoriaArticulosLayout = new javax.swing.GroupLayout(jPanelCategoriaArticulos);
        jPanelCategoriaArticulos.setLayout(jPanelCategoriaArticulosLayout);
        jPanelCategoriaArticulosLayout.setHorizontalGroup(
            jPanelCategoriaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoriaArticulosLayout.createSequentialGroup()
                .addGroup(jPanelCategoriaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoriaArticulosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel10)
                        .addGap(42, 42, 42)
                        .addComponent(txtNombreCategoriaArt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCategoriaArticulosLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCategoriaArticulosLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCategoriaArticulosLayout.createSequentialGroup()
                .addGap(0, 197, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanelCategoriaArticulosLayout.setVerticalGroup(
            jPanelCategoriaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoriaArticulosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelCategoriaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreCategoriaArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categoria Articulos", jPanelCategoriaArticulos);

        javax.swing.GroupLayout jPanelPacksLayout = new javax.swing.GroupLayout(jPanelPacks);
        jPanelPacks.setLayout(jPanelPacksLayout);
        jPanelPacksLayout.setHorizontalGroup(
            jPanelPacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanelPacksLayout.setVerticalGroup(
            jPanelPacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Packs", jPanelPacks);

        javax.swing.GroupLayout jPanelCategoriaPacksLayout = new javax.swing.GroupLayout(jPanelCategoriaPacks);
        jPanelCategoriaPacks.setLayout(jPanelCategoriaPacksLayout);
        jPanelCategoriaPacksLayout.setHorizontalGroup(
            jPanelCategoriaPacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanelCategoriaPacksLayout.setVerticalGroup(
            jPanelCategoriaPacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Categoria Packs", jPanelCategoriaPacks);

        jPanelRRSS.setBackground(new java.awt.Color(153, 204, 255));

        txtRRSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRRSSActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");

        cbxRRSS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnOK.setText("OK");

        btnBuscar.setText("Buscar");

        TblRsResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "RRS_Nombre", "CodigoRS", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ScrollTblRsResultado.setViewportView(TblRsResultado);

        ChkInactivo.setText("Inactivo");

        javax.swing.GroupLayout jPanelRRSSLayout = new javax.swing.GroupLayout(jPanelRRSS);
        jPanelRRSS.setLayout(jPanelRRSSLayout);
        jPanelRRSSLayout.setHorizontalGroup(
            jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRRSSLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRRSSLayout.createSequentialGroup()
                        .addComponent(txtBusqudaRS, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRRSSLayout.createSequentialGroup()
                        .addGroup(jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbxRRSS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRRSS, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(ChkInactivo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(265, 265, 265))
            .addGroup(jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRRSSLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ScrollTblRsResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );
        jPanelRRSSLayout.setVerticalGroup(
            jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRRSSLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRRSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar))
                .addGap(18, 18, 18)
                .addGroup(jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxRRSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK)
                    .addComponent(ChkInactivo))
                .addGap(27, 27, 27)
                .addGroup(jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBusqudaRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
            .addGroup(jPanelRRSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRRSSLayout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(ScrollTblRsResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(151, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("RRSS", jPanelRRSS);

        jPanel12.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setText("Entidad Bancaria");

        jLabel8.setText("Estado");

        txtEntidadBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntidadBancariaActionPerformed(evt);
            }
        });

        jCBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Activo", "Inactivo" }));

        btnIngresar1.setText("Ingresar");
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });

        btnBuscar1.setText("Buscar");

        jtDatosBnc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Entidad Bancaria", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jtDatosBnc);

        jLabel9.setText("Codigo");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        btnMenuInicio.setText("Menu Inicio");

        btnCerrarSesion.setText("Cerrar Sesion");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar1))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(btnMenuInicio)
                                .addGap(145, 145, 145)
                                .addComponent(btnCerrarSesion)))
                        .addGap(0, 349, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(57, 57, 57)
                                        .addComponent(txtCodigo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEntidadBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(btnIngresar1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEntidadBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuInicio)
                    .addComponent(btnCerrarSesion))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBancosLayout = new javax.swing.GroupLayout(jPanelBancos);
        jPanelBancos.setLayout(jPanelBancosLayout);
        jPanelBancosLayout.setHorizontalGroup(
            jPanelBancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBancosLayout.setVerticalGroup(
            jPanelBancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bancos", jPanelBancos);

        javax.swing.GroupLayout jPanelEstados_VentasLayout = new javax.swing.GroupLayout(jPanelEstados_Ventas);
        jPanelEstados_Ventas.setLayout(jPanelEstados_VentasLayout);
        jPanelEstados_VentasLayout.setHorizontalGroup(
            jPanelEstados_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanelEstados_VentasLayout.setVerticalGroup(
            jPanelEstados_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Estados_Venta", jPanelEstados_Ventas);

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Usuario", jPanelUsuario);

        jPanelArticulos.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setText("Nombre");

        jLabel2.setText("Stock");

        ComboBoxArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxArticuloActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria Articulo");

        jLabel4.setText("Fecha de Vencimiento");

        CheckBoxVencimientoArticulo.setText("Sin Vencimiento");

        TableArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Categoría", "Stock", "Fecha Vencimiento"
            }
        ));
        jScrollPane1.setViewportView(TableArticulo);

        btnIngregarArticulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngregarArticulo.setText("Ingresar");

        jLabel6.setText("Id Caegoria");

        javax.swing.GroupLayout jPanelArticulosLayout = new javax.swing.GroupLayout(jPanelArticulos);
        jPanelArticulos.setLayout(jPanelArticulosLayout);
        jPanelArticulosLayout.setHorizontalGroup(
            jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArticulosLayout.createSequentialGroup()
                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelArticulosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelArticulosLayout.createSequentialGroup()
                                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelArticulosLayout.createSequentialGroup()
                                        .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanelArticulosLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(txtStockArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(txtCategoriaArt))
                                .addGap(84, 84, 84)
                                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(btnIngregarArticulo))
                                .addGap(148, 148, 148)
                                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckBoxVencimientoArticulo)
                                    .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtFechaArticulo)
                                        .addComponent(ComboBoxArticulo, 0, 85, Short.MAX_VALUE))))))
                    .addGroup(jPanelArticulosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanelArticulosLayout.setVerticalGroup(
            jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArticulosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStockArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelArticulosLayout.createSequentialGroup()
                        .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelArticulosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(CheckBoxVencimientoArticulo))
                            .addGroup(jPanelArticulosLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCategoriaArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelArticulosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIngregarArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Articulos", jPanelArticulos);

        jPanelComunas.setBackground(new java.awt.Color(153, 204, 255));
        jPanelComunas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelComunas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setText("Nombre");
        jPanelComunas.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabelCodigo.setText("Codigo Comuna");
        jPanelComunas.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        btnIngresarComuna.setText("Ingresar");
        btnIngresarComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarComunaActionPerformed(evt);
            }
        });
        jPanelComunas.add(btnIngresarComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 80, -1));

        txtCodigoComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoComunaActionPerformed(evt);
            }
        });
        jPanelComunas.add(txtCodigoComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 50, -1));

        txtNombreComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreComunaActionPerformed(evt);
            }
        });
        jPanelComunas.add(txtNombreComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));
        jPanelComunas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 58, 880, 10));
        jPanelComunas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 223, 876, 10));

        jButtonMenuInicio.setText("Menu Inicio");
        jPanelComunas.add(jButtonMenuInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 393, -1, -1));

        jButtonCerrarSesion.setText("Cerrar Sesion");
        jPanelComunas.add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 393, -1, -1));
        jPanelComunas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, 70, 71));

        txtBuscarComunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarComunasActionPerformed(evt);
            }
        });
        jPanelComunas.add(txtBuscarComunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 243, 117, -1));

        btnBuscarComuna.setText("Buscar");
        jPanelComunas.add(btnBuscarComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 243, -1, -1));

        TablaComuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Cod_Comuna", "Comuna", "Estado"
            }
        ));
        TablaComuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaComunaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaComuna);

        jPanelComunas.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 283, 407, 92));

        btnModComuna.setText("Modificar");
        btnModComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModComunaActionPerformed(evt);
            }
        });
        jPanelComunas.add(btnModComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 80, -1));

        btnLimpiarComuna.setText("Limpiar");
        jPanelComunas.add(btnLimpiarComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 80, -1));

        btnGroupComunas.add(rbtnActivoComuna);
        rbtnActivoComuna.setText("Activo");
        jPanelComunas.add(rbtnActivoComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 60, -1));

        btnGroupComunas.add(rbtnInactivoComuna);
        rbtnInactivoComuna.setText("Inactivo");
        jPanelComunas.add(rbtnInactivoComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        txtIdComunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdComunasActionPerformed(evt);
            }
        });
        jPanelComunas.add(txtIdComunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 60, -1));

        jLabel12.setText("Estado");
        jPanelComunas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 60, 20));

        jTabbedPane1.addTab("Comunas", jPanelComunas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarComunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarComunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarComunasActionPerformed

    private void txtNombreComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreComunaActionPerformed

    private void txtCodigoComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoComunaActionPerformed

    private void btnIngresarComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarComunaActionPerformed
        // TODO add your handling code here:
        MostrarComuna();
    }//GEN-LAST:event_btnIngresarComunaActionPerformed

    private void ComboBoxArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxArticuloActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void txtEntidadBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntidadBancariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntidadBancariaActionPerformed

    private void txtRRSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRRSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRRSSActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String cli_nombre = txtNombresClientes.getText();
        String cli_apellido = txtApellidosClientes.getText();
        String RUT = txtRut.getText();
        String cli_direccion = txtDireccion.getText();
        String cli_mail = txtMail.getText();
        int cli_telefono = Integer.parseInt(txtTelefono.getText());
        String fecha_nac = txtFechaNacimento.getText();
        String estado;

        if(rActivo.isSelected() == true){
            estado = "A";
        }else if(rInactivo.isSelected() == true){
            estado = "I";
        }else{
            estado = "A";
        }

        try{
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();

            PreparedStatement ps = con.prepareStatement("INSERT INTO cliente (cli_nombre,cli_apellido,RUT,cli_direccion,cli_mail,cli_telefono,fecha_nac,estado) VALUES(?,?,?,?,?,?,?,?)");
            ps.setString(1,cli_nombre);
            ps.setString(2,cli_apellido);
            ps.setString(3,RUT);
            ps.setString(4,cli_direccion);
            ps.setString(5,cli_mail);
            ps.setInt(6,cli_telefono);
            ps.setString(7,fecha_nac);
            ps.setString(8,estado);
            // ps.setInt(9,1);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null,"Registro guardado");

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtApellidosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosClientesActionPerformed

    private void txtNombresClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresClientesActionPerformed

    private void btnModComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModComunaActionPerformed
        // TODO add your handling code here:
        MostrarComuna();
    }//GEN-LAST:event_btnModComunaActionPerformed

    private void TablaComunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaComunaMouseClicked
        // TODO add your handling code here:
        llamarDatosComunas();
    }//GEN-LAST:event_TablaComunaMouseClicked

    private void txtIdComunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdComunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdComunasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox CheckBoxVencimientoArticulo;
    public javax.swing.JCheckBox ChkInactivo;
    public javax.swing.JComboBox<String> ComboBoxArticulo;
    public javax.swing.JScrollPane ScrollTblRsResultado;
    public javax.swing.JTable TablaComuna;
    public javax.swing.JTable TableArticulo;
    public javax.swing.JTable TableCategoriaArt;
    public javax.swing.JTable TblRsResultado;
    public javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    public javax.swing.JButton btnBuscarComuna;
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.ButtonGroup btnGroupComunas;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnIngregarArticulo;
    public javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresar1;
    public javax.swing.JButton btnIngresarComuna;
    public javax.swing.JButton btnLimpiarComuna;
    public javax.swing.JButton btnMenuInicio;
    public javax.swing.JButton btnModComuna;
    public javax.swing.JButton btnOK;
    public javax.swing.JComboBox<String> cbxRRSS;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButtonCerrarSesion;
    public javax.swing.JButton jButtonMenuInicio;
    private javax.swing.JComboBox<String> jCBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelCodigo;
    public javax.swing.JLabel jLabelNombre;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanelArticulos;
    private javax.swing.JPanel jPanelBancos;
    private javax.swing.JPanel jPanelCategoriaArticulos;
    private javax.swing.JPanel jPanelCategoriaPacks;
    private javax.swing.JPanel jPanelClientes;
    public javax.swing.JPanel jPanelComunas;
    private javax.swing.JPanel jPanelEstados_Ventas;
    private javax.swing.JPanel jPanelPacks;
    private javax.swing.JPanel jPanelProveedores;
    private javax.swing.JPanel jPanelRRSS;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable jtDatosBnc;
    public javax.swing.JLabel nombre;
    public javax.swing.JRadioButton rActivo;
    public javax.swing.JRadioButton rInactivo;
    public javax.swing.JRadioButton rbtnActivoComuna;
    public javax.swing.JRadioButton rbtnInactivoComuna;
    public javax.swing.JTextField txtApellidosClientes;
    public javax.swing.JTextField txtBuscarComunas;
    public javax.swing.JTextField txtBusqudaRS;
    public javax.swing.JTextField txtCategoriaArt;
    private javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtCodigoComuna;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtEntidadBancaria;
    public javax.swing.JTextField txtFechaArticulo;
    public javax.swing.JTextField txtFechaNacimento;
    public javax.swing.JTextField txtIdComunas;
    public javax.swing.JTextField txtMail;
    public javax.swing.JTextField txtNombreArticulo;
    private javax.swing.JTextField txtNombreCategoriaArt;
    public javax.swing.JTextField txtNombreComuna;
    public javax.swing.JTextField txtNombresClientes;
    public javax.swing.JTextField txtRRSS;
    public javax.swing.JTextField txtRut;
    public javax.swing.JTextField txtStockArticulo;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
